
###GET
http://localhost:3000/contact/


###POST
POST http://localhost:3000/contact HTTP/1.1
content-type: application/json

{
    "firstName": "Lucas",
    "lastName": "Ramos",
    "email": "lucasboy@gmail.com",
    "age": "15",
    "birthday": "01/12/99",
    "hobbies": "skiing, football",
    "fears": "insects"
  }

###PUT
PUT http://localhost:3000/contact/62917b36139c12da3c4d545d HTTP/1.1
content-type: application/json

{
    "firstName": "Lucas",
    "lastName": "Ramos",
    "email": "oldboy@gmail.com",
    "age": "20",
    "birthday": "01/12/02",
    "hobbies": "skiing, football",
    "fears": "insects"
  }

###DELETE
DELETE http://localhost:3000/contact/6289421a154d60b69642fc7f HTTP/1.1


### GET
https://cse341-bucket.herokuapp.com/contact


###POST
POST https://cse341-bucket.herokuapp.com/contact HTTP/1.1
content-type: application/json

{
    "firstName": "Lucas",
    "lastName": "Ramos",
    "email": "lucasboy@gmail.com",
    "age": "15",
    "birthday": "01/12/99",
    "hobbies": "skiing, football",
    "fears": "insects"
  }
###PUT
PUT https://cse341-bucket.herokuapp.com/contact/62917b36139c12da3c4d545d HTTP/1.1
content-type: application/json

{
    "firstName": "Lucas",
    "lastName": "Ramos",
    "email": "lucasboy@gmail.com",
    "age": "22",
    "birthday": "01/12/01",
    "hobbies": "skiing, football",
    "fears": "insects"
  }

###DELETE
DELETE https://cse341-bucket.herokuapp.com/contact/62917b36139c12da3c4d545d HTTP/1.1
